//auth Action Types
// Create
export const TABLE_CREATION_STARTED = "TABLE_CREATION_STARTED";
export const TABLE_CREATION_SUCCESS = "TABLE_CREATION_SUCCESS";
export const TABLE_CREATION_FAIL = "TABLE_CREATION_FAIL";

//account details
export const TABLE_DETAILS_STARTED = "TABLE_DETAILS_STARTED";
export const TABLE_DETAILS_SUCCESS = "TABLE_DETAILS_SUCCESS";
export const TABLE_DETAILS_FAIL = "TABLE_DETAILS_FAIL";

//Fetch
export const TABLE_FETCH_STARTED = "TABLE_FETCH_STARTED";
export const TABLE_FETCH_SUCCES = "TABLE_FETCH_SUCCES";
export const TABLE_FETCH_FAIL = "TABLE_FETCH_FAIL";

//Update
export const TABLE_UPDATE_STARTED = "TABLE_UPDATE_STARTED";
export const TABLE_UPDATE_SUCCES = "TABLE_UPDATE_SUCCES";
export const TABLE_UPDATE_FAIL = "TABLE_UPDATE_FAIL";

//Delete
export const TABLE_DELETE_STARTED = "TABLE_DELETE_STARTED";
export const TABLE_DELETE_SUCCES = "TABLE_DELETE_SUCCES";
export const TABLE_DELETE_FAIL = "TABLE_DELETE_FAIL";
