export const RESERVATION_CREATION_STARTED = "RESERVATION_CREATION_STARTED";
export const RESERVATION_CREATION_SUCCESS = "RESERVATION_CREATION_SUCCESS";
export const RESERVATION_CREATION_FAIL = "RESERVATION_CREATION_FAIL";

//account details
export const RESERVATION_DETAILS_STARTED = "RESERVATION_DETAILS_STARTED";
export const RESERVATION_DETAILS_SUCCESS = "RESERVATION_DETAILS_SUCCESS";
export const RESERVATION_DETAILS_FAIL = "RESERVATION_DETAILS_FAIL";

//Fetch
export const RESERVATION_FETCH_STARTED = "RESERVATION_FETCH_STARTED";
export const RESERVATION_FETCH_SUCCES = "RESERVATION_FETCH_SUCCES";
export const RESERVATION_FETCH_FAIL = "RESERVATION_FETCH_FAIL";

//Update
export const RESERVATION_UPDATE_STARTED = "RESERVATION_UPDATE_STARTED";
export const RESERVATION_UPDATE_SUCCES = "RESERVATION_UPDATE_SUCCES";
export const RESERVATION_UPDATE_FAIL = "RESERVATION_UPDATE_FAIL";

//Delete
export const RESERVATION_DELETE_STARTED = "RESERVATION_DELETE_STARTED";
export const RESERVATION_DELETE_SUCCES = "RESERVATION_DELETE_SUCCES";
export const RESERVATION_DELETE_FAIL = "RESERVATION_DELETE_FAIL";
